#!/bin/sh
# Name: tmkdir
# Description: make direcatory ij termux home and make a symlink to it
# System: Termux PRoot-Distro
# Author: Ahmad Asaad

mkdir "$TERMUX/home/$1" && ln -s "$TERMUX/home/$1" ~
